name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PLUGIN_NAME: QtExamplePlugin

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Variables
        run: |
          sed -i "s/<plugin_name>/${{ env.PLUGIN_NAME }}/g" CMakeLists.txt
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: prebuild
          path: |
            deploy/package.ini
            src/definitions.hpp
            CMakeLists.txt
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            arch: x64
          - os: ubuntu-latest
            arch: x64
    runs-on: ${{ matrix.os }}
    needs: prebuild
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Download prebuild
        uses: actions/download-artifact@v3
        with:
          name: prebuild
          path: .
      - name: Setup MSVC (Windows only)
        if: matrix.os == 'windows-2019'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
          toolset: 14.0
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          target: 'desktop'
          arch: ${{ matrix.os == 'windows-2019' && 'win64_msvc2019_64' || 'gcc_64' }}
          dir: '${{ github.workspace }}'
          cache: true
          cache-key-prefix: ${{ runner.os }}-${{ matrix.arch }}-Qt
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
      - name: Build
        run: |
          cmake ${{matrix.os == 'windows-2019' && '-A' || ''}} ${{matrix.os == 'windows-2019' && 'x64' || '' }} .
          cmake --build . --config Release
      - name: Rename release (Windows)
        if: matrix.os == 'windows-2019'
        run: |
          mv Release/${{ env.PLUGIN_NAME }}.dll ${{ env.PLUGIN_NAME }}_win64.dll
      - name: Rename release (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mv lib${{ env.PLUGIN_NAME }}.so ${{ env.PLUGIN_NAME }}_linux_amd64.so
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: |
            ${{ env.PLUGIN_NAME }}_win64.dll
            ${{ env.PLUGIN_NAME }}_linux_amd64.so
# Removed the release job as it's no longer needed.
