name: Build for Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PLUGIN_NAME: QtExamplePlugin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true 
      - name: Set Variables
        run: |
          sed -i "s/<plugin_name>/${{ env.PLUGIN_NAME }}/g" CMakeLists.txt
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          target: 'desktop'
          arch: 'gcc_64'
          dir: '${{ github.workspace }}'
          cache: true
          cache-key-prefix: ${{ runner.os }}-Qt
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
      - name: Build
        run: |
          cmake .
          cmake --build . --config Release
      - name: Rename release (Linux)
        run: |
          mv lib${{ env.PLUGIN_NAME }}.so ${{ env.PLUGIN_NAME }}_linux_amd64.so
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PLUGIN_NAME }}_linux_amd64
          path: ${{ env.PLUGIN_NAME }}_linux_amd64.so
